CREATE TABLE USER_TO_GET(
   USER_ID INT
);

INSERT INTO USER_TO_GET (USER_ID) VALUES(1);
INSERT INTO USER_TO_GET (USER_ID) VALUES(2);
INSERT INTO USER_TO_GET (USER_ID) VALUES(3);
INSERT INTO USER_TO_GET (USER_ID) VALUES(4);
INSERT INTO USER_TO_GET (USER_ID) VALUES(5);
INSERT INTO USER_TO_GET (USER_ID) VALUES(6);
INSERT INTO USER_TO_GET (USER_ID) VALUES(7);
INSERT INTO USER_TO_GET (USER_ID) VALUES(8);
INSERT INTO USER_TO_GET (USER_ID) VALUES(9);
INSERT INTO USER_TO_GET (USER_ID) VALUES(10);
INSERT INTO USER_TO_GET (USER_ID) VALUES(11);
INSERT INTO USER_TO_GET (USER_ID) VALUES(12);
INSERT INTO USER_TO_GET (USER_ID) VALUES(13);
INSERT INTO USER_TO_GET (USER_ID) VALUES(14);
INSERT INTO USER_TO_GET (USER_ID) VALUES(15);
INSERT INTO USER_TO_GET (USER_ID) VALUES(16);
INSERT INTO USER_TO_GET (USER_ID) VALUES(17);
INSERT INTO USER_TO_GET (USER_ID) VALUES(18);
INSERT INTO USER_TO_GET (USER_ID) VALUES(19);
INSERT INTO USER_TO_GET (USER_ID) VALUES(20);
INSERT INTO USER_TO_GET (USER_ID) VALUES(21);
INSERT INTO USER_TO_GET (USER_ID) VALUES(22);
INSERT INTO USER_TO_GET (USER_ID) VALUES(23);
